version: '3.8'

services:
  web:
    image: pelish/yamdb:latest
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=yamdb
      - POSTGRES_USER=yamdb_user
      - POSTGRES_PASSWORD=yamdb_password
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: