version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=yamdb
      - POSTGRES_USER=yamdb_user
      - POSTGRES_PASSWORD=yamdb_password
    env_file:
      - ./.env
  web:
    build: .
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env