# Generated by Django 3.0.5 on 2020-12-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20201203_1030'),
        ('api', '0005_auto_20201203_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='titles.Title'),
        ),
    ]
