# Generated by Django 3.0.5 on 2020-12-03 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20201203_1030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20201203_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='title_id',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('title', 'author')},
        ),
    ]
